# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
      - id: sort-simple-yaml
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
  - repo: https://github.com/psf/black
    rev: "25.1.0"
    hooks:
      - id: black
  - repo: https://github.com/NixOS/nixfmt
    rev: "v1.0.0"
    hooks:
      - id: nixfmt
        name: nixfmt
        entry: bash -c 'case "$(uname -s)" in MINGW*|CYGWIN*|MSYS*) exit 0;; Linux*|Darwin*) nixfmt "$@";; *) exit 1;; esac' --
        language: system
        files: \.nix$
