name: Nix Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  nix-build:
    name: Nix build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nix-type: [default, flake]
    steps:
      - uses: actions/checkout@v4
        
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          
      - name: Build with traditional Nix
        if: matrix.nix-type == 'default'
        run: |
          nix-build
          
      - name: Build with Nix flakes
        if: matrix.nix-type == 'flake'
        run: |
          nix --experimental-features "nix-command flakes" build
          
      - name: Test app execution (traditional)
        if: matrix.nix-type == 'default'
        run: |
          result/bin/openconnect-sso --help
          
      - name: Test app execution (flake)
        if: matrix.nix-type == 'flake'
        run: |
          result/bin/openconnect-sso --help
          
  nix-shell:
    name: Nix shell environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          
      - name: Test nix-shell environment
        run: |
          nix-shell --run "echo 'Nix shell environment loaded successfully'"
          nix-shell --run "which make"
          nix-shell --run "which python3"
          
  nix-overlays:
    name: Test Nix overlays
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          
      - name: Test overlay functionality
        run: |
          # Test that the overlay can be imported
          nix-instantiate --eval -E "
            let 
              pkgs = import <nixpkgs> { overlays = [ (import ./overlay.nix) ]; };
            in
              pkgs ? openconnect-sso
          "